root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/worker/main.go"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "bin"]
  include_ext = ["go", "env"]
  exclude_regex = ["_test.go"]
